---
# Ansible Playbook to print out /etc/os-release
# Filename: print_os_release.yml

- name: Print OS Release Information
  hosts: all  # This will run on all hosts defined in your inventory
  become: false  # No need for sudo privileges to read /etc/os-release in most cases
  
  tasks:
    - name: Get OS release information
      command: cat /etc/os-release
      register: os_release
      changed_when: false  # This ensures the task always reports as "ok" rather than "changed"
      
    - name: Display OS release information
      debug:
        msg: "{{ os_release.stdout_lines }}"
        
    - name: Extract OS name
      shell: grep '^NAME=' /etc/os-release | cut -d'"' -f2
      register: os_name
      changed_when: false
      
    - name: Extract OS version
      shell: grep '^VERSION=' /etc/os-release | cut -d'"' -f2
      register: os_version
      changed_when: false
      
    - name: Display summary
      debug:
        msg: "OS: {{ os_name.stdout }}, Version: {{ os_version.stdout }}"
